### ISSUE TITLE
Does this work at all?

### ISSUE THREAD

**Issue by optikalefx** [samcday/node-google-spreadsheets#28]
I've tried 2 of the examples so far, both come back with errors. Normal looking spreadsheet http://cl.ly/image/1n0g420f3q1N

My code 

```js
GoogleSpreadsheets({
		    key: "MYKEY"
		}, function(err, spreadsheet) {
		    spreadsheet.worksheets[0].cells({
		        range: "A1R1:A1CR2"
		    }, function(err, result) {
		    	console.log(result);
		    });
		});
```

Which gives me 

```
spreadsheet.worksheets[0].cells({
							           ^
TypeError: Cannot read property 'worksheets' of null
```

And if I try one of the direct methods I get 

```
node_modules/google-spreadsheets/lib/spreadsheets.js:238
    if(typeof data.entry !== "undefined" && data.entry !== null) {
                  ^
TypeError: Cannot read property 'entry' of undefined
```

And yes I've my spreadsheet public for unauthed testing.  Thoughts?

**Comment by optikalefx** [comment]
I've also tried without the range

**Comment by samcday** [comment]
@optikalefx I just ran the tests for the project (which load a test spreadsheet from real Google API) and it all seems to be working. Can you debug a little further and come up with a reproducible test case I can play with?

**Comment by optikalefx** [comment]
So I ran your test, and it worked fine. I replaced just your key with my key and got the following.

```
err [TypeError: Cannot read property 'title' of undefined]
```

Where this is the response from your API. So I guess it's reading it, but can't read my data set? The screenshot above of my sheet. Here is an open google doc of a copy of the spreadsheet so you could test it.  >>>>> https://docs.google.com/spreadsheets/d/1ZSYZYnk60MmPp-JPGKIhN3M8-WUMtCsWXTLakYE9-cA/edit#gid=0

**Comment by optikalefx** [comment]
What's odd is that when I go to the URL you're forming directly https://spreadsheets.google.com/feeds/worksheets/1ZSYZYnk60MmPp-JPGKIhN3M8-WUMtCsWXTLakYE9-cA/public/values?alt=json

Google says this is not public.  But it definitely is public. http://cl.ly/image/032g3o402h11

**Comment by samcday** [comment]
@optikalefx I think I know what the problem is now.

Take a look at the [Anonymous Requests](https://github.com/samcday/node-google-spreadsheets#anonymous-requests) section of the README. It's not enough to simply make your spreadsheet public, you also have to make it "published".

You do this by clicking `File -> Publish to the Web...` from the spreadsheet editor.

When I do that for the spreadsheet that works in tests, I see something like this:

![image](https://cloud.githubusercontent.com/assets/531550/9699462/7d6ad01c-5427-11e5-92a5-d89b593c3487.png)

**Comment by optikalefx** [comment]
That was it. Thanks! You should update the readme.
